nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0

    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)

#    models:
#        names:
#            - { alias: Product,        type: App\Application\Command\Product\Request\CreateProduct }
#            - { alias: StoreManager,        type: App\Application\Command\StoreManager\Request\CreateStoreManager }
#            - { alias: Store,        type: App\Application\Command\Store\Request\CreateStore }
#            - { alias: Stock,        type: App\Application\Command\Stock\Request\CreateStock }