App\Domain\Entity\Product:
    type: entity
    repositoryClass: App\Infrastructure\Repository\ProductRepository
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    lifecycleCallbacks: {  }
